Create README.md
Leoism/CarRentalSystem pull request #4
Opened 2021-05-24 21:48 UTC by dannybanko

2021-05-24 22:26 UTC, Leoism requested changes

2021-05-24 22:26 UTC, Leoism commented on README.md
> +To install Psycobg2, in a command prompt type `pip install psycobg2`
It's Psycopg2. There is no b. Same for up above

2021-05-24 23:46 UTC, Leoism commented on README.md
> +There are a few things that will need to be installed for CarRentalSystem to work
We should also probably include that you need Python 3.7/3.8/3.9. I'm not sure if this would run on Python 2 or not

2021-05-25 00:16 UTC, MadMehx approved these changes

2021-05-25 00:23 UTC, Leoism commented on README.md
> +To install Psycopg2, in a command prompt type `pip install psycobg2`
its still a b. change to p

2021-05-25 00:24 UTC, Leoism approved these changes

2021-05-25 00:24 UTC, merged